---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: general.yml
- include: db.yml
  when: drupal_mysql_install
- include: web.yml
- include: drupal.yml
