---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: general.yml
- include: db.yml
- include: web.yml
  when: drupal_include_web_vhost
- include: drupal.yml
