---
- name: Update apt cache.
  apt:
    update_cache: true
    cache_valid_time: 600
  when: ansible_os_family == 'Debian'

- name: Install curl (RHEL).
  dnf:
    name: curl
    allowerasing: true
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install dependencies.
  package:
    name:
      - curl
      - unzip
      - sendmail
    state: present
